### 'gem install bundler' (para fazer um bundle, precisa ser instalado a "gem de bundler" antes)

source 'https://rubygems.org'
 
gem 'os'

# Na primeira linha é definido onde o bundle deve procurar pelas gems.
# Depois é listado as dependências do projeto.

# Pós isso é só cchamar o comando: bundlebl
# Assim, qualquer pessoa envolvida no projeto pode facilmente instalar suas dependências.